
# The URL the site will be built for
base_url = "/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "anemone"
# theme = "after-dark"


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
list_pages = false
toc = true

header_nav = [
  {url = "/", name_en = "Home"},
  { url = "https://github.com/paradoxedmind", name_en = "Github" },
  {url = "/blog", name_en = "Blog"},
  { url = "/about", name_en = "About" },
  # { url = "/journal", name_en = "/journal/", name_fr = "/journal/" },
]

twitter_card = false
